CREATE DATABASE IF NOT EXISTS `customer-db`;
GRANT ALL PRIVILEGES ON *.* TO 'indir' IDENTIFIED BY "root";
CREATE DATABASE IF NOT EXISTS `order-db`;
GRANT ALL PRIVILEGES ON *.* TO 'indir' IDENTIFIED BY "root";
